set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(ARM_NONE_EABI_PREFIX arm-none-eabi CACHE STRING "GNU Arm tool prefix")

find_program(CMAKE_C_COMPILER NAMES ${ARM_NONE_EABI_PREFIX}-gcc REQUIRED)
find_program(CMAKE_ASM_COMPILER NAMES ${ARM_NONE_EABI_PREFIX}-gcc REQUIRED)
find_program(CMAKE_OBJCOPY NAMES ${ARM_NONE_EABI_PREFIX}-objcopy REQUIRED)
find_program(CMAKE_SIZE NAMES ${ARM_NONE_EABI_PREFIX}-size REQUIRED)
